export default {
  name: 'home',
  type: 'document',
  title: 'Home',
  description: 'Conteúdos da página Home',
  fields: [
    {
      name: 'title',
      type: 'string',
      title: 'Título',
      description: 'Texto que ficará em evidência na página.',
    },
    {
      name: 'description',
      type: 'string',
      title: 'Descrição',
      description: 'Texto que dará contexto a página.',
    },
    {
      name: 'imageURL',
      type: 'url',
      title: 'Imagem URL',
      description: 'URL da imagem que ficará em evidência na página.',
    },
    {
      name: 'imageAlt',
      type: 'string',
      title: 'Imagem Alt',
      description: 'Texto alternativo para a imagem em evidência na página.',
    },
    {
      name: 'heroButtonLabel',
      type: 'string',
      title: 'Label do botão do Hero',
      description: 'Label do botão do Hero.',
    },
    {
      name: 'heroTopics',
      type: 'array',
      title: 'Tópicos do Hero',
      description: 'Tópicos que descrevem o conteúdo da podcast.',
      of: [{type: 'string'}],
    },
    {
      name: 'simulationSectionTitle',
      type: 'string',
      title: 'Título da seção de simulação',
      description: 'Título da seção de simulação.',
    },
    {
      name: 'simulationSectionDescription',
      type: 'string',
      title: 'Descrição da seção de simulação',
      description: 'Descrição da seção de simulação.',
    },
    {
      name: 'simulationSectionTopics',
      type: 'array',
      title: 'Tópicos da seção de simulação',
      description: 'Tópicos da seção de simulação.',
      of: [{type: 'string'}],
    },
    {
      name: 'simulationSectionMemberButtonLabel',
      type: 'string',
      title: 'Label do botão da seção de simulação para voluntário',
      description: 'Label do botão da seção de simulação para voluntário.',
    },
    {
      name: 'simulationSectionMentorButtonLabel',
      type: 'string',
      title: 'Label do botão da seção de simulação para mentor',
      description: 'Label do botão da seção de simulação para mentor.',
    },
    {
      name: 'podcastSectionTitle',
      type: 'string',
      title: 'Título da seção de podcast',
      description: 'Título da seção de podcast.',
    },
    {
      name: 'podcastSectionDescription',
      type: 'string',
      title: 'Descrição da seção de podcast',
      description: 'Descrição da seção de podcast.',
    },
    {
      name: 'popcornClubSectionTitle',
      type: 'string',
      title: 'Título da seção clube do pipoca',
      description: 'Título da seção clube do pipoca.',
    },
    {
      name: 'popcornClubSectionDescription',
      type: 'string',
      title: 'Descrição da seção clube do pipoca',
      description: 'Descrição da seção clube do pipoca.',
    },
    {
      name: 'popcornClubSectionButtonLabel',
      type: 'string',
      title: 'Label do botão da seção clube do pipoca',
      description: 'Label do botão da seção clube do pipoca.',
    },
    {
      name: 'agileTrailSectionTitle',
      type: 'string',
      title: 'Título da seção de trilha ágil',
      description: 'Título da seção de trilha ágil.',
    },
    {
      name: 'agileTrailSectionDescription',
      type: 'string',
      title: 'Descrição da seção de trilha ágil',
      description: 'Descrição da seção de trilha ágil.',
    },
    {
      name: 'agileTrailSectionButtonLabel',
      type: 'string',
      title: 'Label do botão da seção de trilha ágil',
      description: 'Label do botão da seção de trilha ágil.',
    },
    {
      name: 'popcornIndicationSectionTitle',
      type: 'string',
      title: 'Título da seção Pipoca Indica',
      description: 'Título da seção Pipoca Indica.',
    },
    {
      name: 'popcornIndicationSectionDescription',
      type: 'string',
      title: 'Descrição da seção Pipoca Indica',
      description: 'Descrição da seção Pipoca Indica.',
    },
    {
      name: 'popcornIndicationSectionButtonLabel',
      type: 'string',
      title: 'Label do botão da seção Pipoca Indica',
      description: 'Label do botão da seção Pipoca Indica.',
    },
    {
      name: 'newsletterSectionTitle',
      type: 'string',
      title: 'Título da seção de newsletter',
      description: 'Título da seção de newsletter.',
    },
    {
      name: 'newsletterSectionDescription',
      type: 'string',
      title: 'Descrição da seção de newsletter',
      description: 'Descrição da seção de newsletter.',
    },
    {
      name: 'newsletterSectionButtonLabel',
      type: 'string',
      title: 'Label do botão da seção de newsletter',
      description: 'Label do botão da seção de newsletter.',
    },
  ],
}
